services:
  n_m3u8dl-re-streamer:
    image: ataaki/n_m3u8dl-re-streamer:latest
    container_name: n_m3u8dl-re-streamer
    ports:
      - "8080:8080"
    environment:
      N_M3U8DL_RE_PARAMS: ""
      STREAM_FILE: "output.m3u8"
    restart: unless-stopped
